# Generated by Django 5.2.7 on 2025-10-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_city_order_notes_order_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Order Confirmed'), ('packed_ready', 'Packed / Ready to Deliver'), ('en_route', 'En Route/Delivering'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_confirmation', max_length=30),
        ),
    ]
