# Generated by Django 5.2.7 on 2025-11-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_archived_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_image',
            field=models.ImageField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
