# Generated by Django 5.2.7 on 2025-11-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_order_invoice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comingsoon',
            name='image',
            field=models.ImageField(default='default.png', upload_to='comingsoon/'),
        ),
    ]
