# Generated by Django 5.2.7 on 2025-11-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_banner_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_image',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
