# Generated by Django 6.0.3 on 2026-03-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kathieskitchen', '0003_user_alter_products_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
