# Generated by Django 6.0.3 on 2026-03-17 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kathieskitchen', '0004_alter_products_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComingSoonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coming_soon_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('coming_soon_image', models.CharField(blank=True, max_length=255, null=True)),
                ('coming_soon_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kathieskitchen.products')),
            ],
            options={
                'verbose_name': 'Coming Soon Product',
                'verbose_name_plural': 'Coming Soon Products',
            },
        ),
    ]
